# Generated by Django 2.1.3 on 2018-12-19 14:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RulesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('category_details', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='RulesRegulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jecApp.RulesCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, choices=[('chairman', 'Chairman'), ('vice-chairman', 'Vice Chairman'), ('general-secretary', 'General Secretary'), ('board-member-1', 'Board Member 1'), ('board-member-2', 'Board Member 2'), ('board-member-3', 'Board Member 3')], max_length=100, null=True)),
                ('rank', models.CharField(choices=[('founder', 'Founder'), ('ordinary', 'Ordinary'), ('governing', 'Governing'), ('co-governing', 'Co-Governing'), ('advisory', 'Advisory')], max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('education', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
