# Generated by Django 2.1.3 on 2018-12-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jecApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='xyz', upload_to=''),
            preserve_default=False,
        ),
    ]
