# Generated by Django 2.1.3 on 2018-12-26 19:08

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jecApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='')),
                ('message_test', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='shareholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jecApp.Shareholder'),
        ),
    ]
