# Generated by Django 2.1.3 on 2018-12-15 13:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jecApp', '0002_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
