# Generated by Django 2.1.3 on 2018-12-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jecApp', '0002_rulescategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesregulation',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
