# Generated by Django 2.1.3 on 2018-12-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jecApp', '0002_auto_20181227_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_test',
            new_name='message_text',
        ),
    ]
