# Generated by Django 2.1.3 on 2018-12-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jecApp', '0003_rulesregulation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesregulation',
            name='image',
            field=models.ImageField(default='this_is_image', upload_to=''),
            preserve_default=False,
        ),
    ]
