# Generated by Django 2.1.3 on 2018-12-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('police_station', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
