# Generated by Django 2.1.3 on 2018-12-20 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='mobile',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='police_station',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='postal_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
