# Generated by Django 2.1.3 on 2018-12-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sutitle', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, help_text="Don't upload image, if it is not image gallery category", null=True, upload_to='')),
                ('video', models.URLField(blank=True, help_text="link from youtube or vimeo. Don't upload image, if it is not image gallery category", null=True)),
                ('pdf', models.FileField(blank=True, help_text='only for seminar gallery', null=True, upload_to='')),
            ],
        ),
    ]
